language: python
python:
  - "3.7"
env:
  # TODO: remove this when docker is integrated into the build process
  - SQLALCHEMY_DATABASE_URI='sqlite:///test.sqlite3'
install:
  - pip install -r user_service/requirements.txt
script:
  - pytest