version: '3'
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbit-node1
    ports:
      - "5672:5672"
    hostname: rabbit-localhost
  mysql_db:
    image: mysql:8.0.31
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: imsuser
      MYSQL_PASSWORD: imsuser_pass
      MYSQL_DATABASE: image_service
    container_name: mysequel
    ports:
      - "3306:3306"
  postgres_db:
    image: postgres:9.6.17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vistagrid
    container_name: postgres_db
  jwt_nginx:
    image: lewisemm/vistagrid-nginx:v1.24.0
    build:
      context: reverseproxy/
    container_name: vistagrid_ngx
    ports:
      - "5001:5001"
  user_service:
    image: user_service:1.0
    build:
      context: user_service/
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@postgres_db:5432/vistagrid
      JWT_SECRET_KEY: 'super-secret'
      USER_SERVICE_CONFIG_MODULE: user_service.config.config.DevConfig
    ports:
      - "5000:5000"
    container_name: user_service
    depends_on:
      - postgres_db
      - jwt_nginx
  image_service:
    image: image_service:v0.1
    build:
      context: image_service/
    environment:
      DJANGO_SETTINGS_MODULE: $IMAGE_SERVICE_DJANGO_SETTINGS_MODULE
      DATABASE_URL: $IMAGE_SERVICE_DATABASE_URL
      SECRET_KEY: $IMAGE_SERVICE_SECRET_KEY
      AWS_SECRET_ACCESS_KEY: $IMAGE_SERVICE_AWS_SECRET_ACCESS_KEY
      AWS_ACCESS_KEY_ID: $IMAGE_SERVICE_AWS_ACCESS_KEY_ID
      S3_BUCKET: $IMAGE_SERVICE_S3_BUCKET
      CELERY_BROKER_URL: $IMAGE_SERVICE_CELERY_BROKER_URL
      AUTH_SERVICE_URL: $IMAGE_SERVICE_AUTH_SERVICE_URL
    ports:
    container_name: image_service
      - "8000:8000"
    depends_on:
      - mysql_db
      - rabbitmq
      - jwt_nginx
    command: [
      "./wait-for-it.sh", "mysql_db:3306", "-t", "40", "--",
      "python", "manage.py", "runserver", "0.0.0.0:8000"
    ]
