version: '3'
services:
  postgres_db:
    image: postgres:9.6.17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vistagrid
    container_name: postgres_db
  user_service:
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@postgres_db:5432/vistagrid
      JWT_SECRET_KEY: 'super-secret'
      USER_SERVICE_CONFIG_MODULE: user_service.config.config.DevConfig
    ports:
      - "5000:5000"
    container_name: user_service
    depends_on:
  image:
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/vistagrid
    ports:
      - "5001:5000"
    depends_on:
      - db
      - postgres_db
