apiVersion: v1
kind: Service
metadata:
  labels:
    service: imageservice-svc
  name: imageservice-svc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: imageservice-deployment
