apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: imageservice-deployment
  name: imageservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: imageservice-deployment
  template:
    metadata:
      labels:
        service: imageservice-deployment
    spec:
      containers:
      - image: lewisemm/imageservice:v0.1
        name: imageservice
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        env:
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: SQLALCHEMY_DATABASE_URI
