apiVersion: v1
kind: Service
metadata:
  labels:
    service: user-service
  name: user-service
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: user-deployment
