apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy-service
  name: reverseproxy-service
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: reverseproxy-deployment
