name: vistagrid-backend-k8s
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SECRET_KEY: 'continous-integration-secret-key'

permissions:
  contents: read

jobs:
  test_user_service:
    name: Test user_service
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: 'localhost:5000'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r user_service/requirements.txt
    - name: Test user_service with pytest
      run: |
        pytest user_service
  test_image_service:
    name: Test image_service
    runs-on: ubuntu-latest
    defaults:
      runs:
        working-directory: image_service
    env:
      DJANGO_SETTINGS_MODULE: 'image_service.settings.dev_settings'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install project dependencies
      run: |
        pipenv install
    - name: Test image_service with django.test.TestCase
      run: |
        python manage.py test
