name: vistagrid-backend-k8s
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SECRET_KEY: 'continous-integration-secret-key'

permissions:
  contents: read

jobs:
  test_user_service:
    name: Test user_service
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: 'localhost:5000'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: user_service
    - name: Test user_service with pytest
      run: pytest
      working-directory: user_service
  test_image_service:
    name: Test image_service
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: 'image_service.settings.dev_settings'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv
    - name: Install project dependencies
      run: pipenv install --system --dev
      working-directory: image_service
    - name: Test image_service with rest_framework.test.APITestCase
      run: ./manage.py test
      working-directory: image_service
